# Generated by Django 3.2.6 on 2021-08-16 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('documento', models.CharField(max_length=20)),
                ('nombres', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.CharField(max_length=50)),
                ('nit', models.CharField(max_length=50)),
                ('numfactura', models.CharField(max_length=60)),
                ('Cli_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cruds.clientes')),
            ],
            options={
                'db_table': 'facturas',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreusuario', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='FacturasProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_fact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cruds.facturas')),
                ('id_produ', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cruds.product')),
            ],
            options={
                'db_table': 'facturasproduct',
            },
        ),
    ]
